### ISSUE TITLE
How to use JPEEK

### ISSUE THREAD

**Issue by lokeshmekala** [cqfn/jpeek#521]
I'm not able to use the tool. I didn't understand by "java -jar jpeek-jar-with-dependencies.jar --sources . --target ./jpeek" what is "sources", "target" here. 
When I try to execute the above command I'm getting 
"Exception in thread 'main' java.lang.IllegalArgumentException: exactly two arguments are required: source and output directory. I specified the path even though I'm getting same exception.  To be specific this is the exact command I used :
java -jar jpeek-0.9-jar-with-dependencies.jar -- C:\Users\name\Downloads\TestIQ3 . -- C:\Users\name\Downloads\Teligram_Desktop ./jpeek

Thank you for your help!

**Comment by 0crat** [comment]
Job `gh:cqfn/jpeek#521` is not assigned, can't get performer
