### ISSUE TITLE
redeploy

### ISSUE THREAD

**Issue by yegor256** [cqfn/jpeek#531]
Let's redeploy it

**Comment by yegor256** [comment]
@rultor release, tag is `0.30.26`

**Comment by yegor256** [comment]
@rultor release, tag is `0.31.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.31.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.31.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.31.1`

**Comment by 0crat** [comment]
Job `gh:cqfn/jpeek#531` is not assigned, can't get performer
