### ISSUE TITLE
refresh

### ISSUE THREAD

**Issue by yegor256** [cqfn/jpeek#534]

**Comment by yegor256** [comment]
@rultor release, tag is `0.32.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.32.0`

**Comment by yegor256** [comment]
@rultor stop

**Comment by yegor256** [comment]
@rultor release, tag is `0.32.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.32.0`

**Comment by 0crat** [comment]
Job `gh:cqfn/jpeek#534` is not assigned, can't get performer
