### ISSUE TITLE
release with live settings file

### ISSUE THREAD

**Issue by yegor256** [cqfn/jpeek#536]

**Comment by yegor256** [comment]
@rultor release, tag is `0.32.1`

**Comment by 0crat** [comment]
Job `gh:cqfn/jpeek#536` is not assigned, can't get performer

**Comment by yegor256** [comment]
@rultor release, tag is `0.32.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.32.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.32.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.32.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.32.2`
